baseURL = "https://nekolicio.us/"
languageCode = "en-us"
title = "nekolicio.us"
theme = "hugo-ink"
copyright = "© 2022 Victor Neo. Licensed under CC BY-NC International License."
summaryLength = 4

[params]
	subtitle = "Victor's Writings"

        avatar = "/images/profile.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "auto"
	customCSS = "css/custom.css"
	customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.


[[menu.main]]
name = "All Posts"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2


[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/victorneo"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/victorneo"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"
